api_servers:
  - auth: null
    url: http://127.0.0.1:5000/encoding/report
completed_cleanup_delay: 604800
email_body: /etc/encodebox/email_body.j2
email_host: smtp.gmail.com
email_password: 1kLRy0LUlZ1HQFde
email_recipients: ['aaron@sigalamedia.com', 'david.fischer.ch@gmail.com']
email_username: encodebox.test@gmail.com
filenames_seed: 499Qm1NKiZmYYE5Q
hd_smil_template: /etc/encodebox/hd.smil
hd_transcode_passes:
- - ffmpeg
  - '{input}'
  - '{tmp}/a.wav'
  - '-analyzeduration 2147480000 -ar 48000 -ac 2'
- 'neroAacEnc -cbr 64000 -lc -if "{tmp}/a.wav" -of "{tmp}/a.mp4"'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=1920x1080" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 2000 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 2000 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_2000.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=1280:720" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 1500 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 1500 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_1500.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=1024:576" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 1200 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 1200 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_1200.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=640:360" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 900 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 900 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_900.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=384:216" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 400 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 400 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_400.mp4'
  - '-vcodec copy -acodec copy'
local_directory: /var/www/data
remote_directory: username@host_ip:/usr/local/WowzaStreamingEngine/content
remote_url: 'http://host_ip:1935/vod/content/{publisher_id}/{product_id}/smil:{name}.smil/playlist.m3u8'
sd_smil_template: /etc/encodebox/sd.smil
sd_transcode_passes:
- - ffmpeg
  - '{input}'
  - '{tmp}/a.wav'
  - '-analyzeduration 2147480000 -ar 48000 -ac 2'
- 'neroAacEnc -cbr 32000 -lc -if "{tmp}/a.wav" -of "{tmp}/a.mp4"'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=896:504" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 1200 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 1200 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_1200.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=640:360" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 900 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 900 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_900.mp4'
  - '-vcodec copy -acodec copy'
- - ffmpeg
  - '{input}'
  - '{tmp}/v.y4m'
  - '-r 25 -vf "scale=384:216" -aspect 16:9 -f yuv4mpegpipe -pix_fmt yuv420p -vsync 1 -g 100 -keyint_min 100 -movflags frag_keyframe'
- - x264
  - '{tmp}/v.y4m'
  - null
  - '--pass 1 --fps 25 --bitrate 400 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - x264
  - '{tmp}/v.y4m'
  - '{tmp}/v.h264'
  - '--pass 2 --fps 25 --bitrate 400 --preset slow --profile main --no-scenecut --stats "{tmp}/x264pass.log"'
- - ffmpeg
  - ['{tmp}/v.h264', '{tmp}/a.mp4']
  - '{out}/{name}_400.mp4'
  - '-vcodec copy -acodec copy'
